[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-puppeteer",
]

[mcp_servers.context7.env]
PUPPETEER_LAUNCH_OPTIONS = '{ "defaultViewport": { "width": 1920, "height": 960 }, "args": ["--window-size=1920,960"] }'

[mcp_servers.puppeteer]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-puppeteer",
]

[mcp_servers.puppeteer.env]
PUPPETEER_LAUNCH_OPTIONS = '{"defaultViewport": {"width": 1920, "height": 960}, "args": ["--window-size=1920,960"]}'

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
BASH_MAX_OUTPUT_LENGTH = "100000"
BASH_DEFAULT_TIMEOUT_MS = "2000000"
CLAUDE_CODE_NOTIFY = "simple"
